### ISSUE TITLE
Pan features need to be double-checked

### ISSUE THREAD

**Issue by paulkass** [paulkass/BirdBoxBuilder#1]
I tried pressing various buttons on my physical mouse, none of them initialized any visible pan features. 

Their activation should probably be double-checked.

**Comment by clarencechen** [comment]
I could change it to the right mouse button...
Your toLowerCase() function needs to be fixed too...

**Comment by paulkass** [comment]
Closed with d6bd9c40400714e308f598a1ffc9be39d9445090.
